### ISSUE TITLE
[Feature] Add an active status

### ISSUE THREAD

**Issue by prysme01** [killemov/Shift#17]
Hello, First of all thanks for this webui for transmission.

I would like to see an active status like in the original transmission webui that show currently active torrent (uploading and downloading)

**Comment by killemov** [comment]
In Shift the most important non-static attribute of a torrent is its status. The value "Active" does not exist within the transmission specification. As an aggregate of Downloading and Seeding torrents it will not work in Shift because the interface visually changes between the two statuses and the information retrieved from transmission changes also. It is, for example, useless to retrieve percentDone again and again when the torrent is seeding.
