### ISSUE TITLE
adding trackers to torrents (using FreeBSD): not working

### ISSUE THREAD

**Issue by mrjayviper** [killemov/Shift#23]
so I have tried the above and it's not working

some info:
- ps | grep transmission tells me the software is run using the transmission user
- the torrents folder is owned by the transmission user
- I copied a list fron ngosang and tried adding it to --all-- torrents (I pressed the add trackers several times)
- I tried on latest firefox/chrome

any ideas what I could be doing wrong? Thanks

**Comment by killemov** [comment]
You did nothing wrong.

I did a debug session on version 3.00 (bb6b5a062e) and found that adding some trackers to all torrents indeed has stopped working. Transmission responds with success but nothing happens. I also tried to add these same trackers to an individual torrent and that works just like it should. For both ways the exact same single function is used. When adding trackers to all torrents an empty array is used as a parameter to indicate ALL torrents instead of an array with a single id. So the problem appears to be a change in how an empty array used to be interpreted as ALL torrents. Maybe @ckerr from the Transmission team could give some insight. I will file an issue right away.

**Comment by ckerr** [comment]
I believe that it's incorrect to pass an empty array `[]` of ids and expect Transmission to treat that as shorthand for 'all torrents'. The spec back to 2.81 (and possibly older? 2.81 is as far back as I looked) says that _omitting_ the `ids` parameter is the way to apply to all torrents. It says nothing about empty arrays.

Looks like the issue may be coming from https://github.com/killemov/Shift/blob/e32e0f9883d8443aaf90be94efbdf1c84b0d8681/shift.js#L392 where `[]` is used as the default `ids` parameter if none is provided. I haven't read the code fully but maybe this should be more like https://github.com/transmission/transmission/blob/0973cfd96d29546589a6952847edec26c59389f7/web/src/remote.js#L129 where `ids` is left out entirely unless provided by the caller.

**Comment by killemov** [comment]
@mrjayviper Looking at the changes for the RPC-spec for 4.0 this functionality may become deprecated in the near future. This because the field trackerAdd will become deprecated. @ckerr Maybe NOT deprecate the trackerAdd field?

**Comment by ckerr** [comment]
> @ckerr Just a thought after committing this. Maybe introduce an explicit "all" string ( ids: "all" ) to prevent possible damaging effects.

I'd be happy to review a PR that adds that, if you want to write it. Sounds like a nice API quality improvement.
